### ISSUE TITLE
File monitoring

### ISSUE THREAD

**Issue by riklempens** [oversight/wmiprobe#7]
As an Oversight user I want to monitor some properties from specific files

WQL Query:
```
"select name,LastAccessed,LastModified,filesize, Readable, Writeable, Hidden, System \
   from cim_datafile where \
  name='c:\\\program files\\\Common Files\\\Services\\\verisign.bmp' \
  OR name='c:\\\pagefile.sys'"
```

Example output

```
FileSize: 738197504
Hidden: True
LastAccessed: 2022-06-15 23:58:22.954782+02:00
LastModified: 2022-06-15 23:58:22.954782+02:00
Name: c:\pagefile.sys
Readable: True
System: True
Writeable: True

FileSize: 2702
Hidden: False
LastAccessed: 2018-09-15 08:12:48.847935+01:00
LastModified: 2018-09-15 08:12:48.847935+01:00
Name: c:\program files\Common Files\Services\verisign.bmp
Readable: True
System: False
Writeable: True
```

**Comment by joente** [comment]
Add a new check (both in v2 and v3). Note that the name convention for v3 is slightly different from v2. The wmiProbe configuration tab on the Oversight website should get an option to ask the user for files to be checked.
If no files are given, this check should not return any data. In v3 this means the check should return with an IgnoreCheckException. With v2 the IgnoreResultException can be raised. Once a file is given, this Check must build a Query with the given files joined with an `OR` statement.

**Comment by joente** [comment]
Be careful with `\` in the file name.

- A user needs to insert for example: `C:\Program Files\test.txt`
- A user should see the fie in the list as given, thus:  `C:\Program Files\test.txt`
- The probe needs to correct the `\` so the query will work.
-
